// Signs/verifies the `cliente`+`modo`+`ts` query params used by the WhatsApp
// onboarding link (src/pages/[lang]/connect.astro) so a link can only be
// generated by someone who holds WHATSAPP_LINK_SECRET (done via
// src/pages/es/admin-links.astro), without needing to persist a list of
// valid links anywhere.

import { createHmac, timingSafeEqual } from "node:crypto";

/**
 * Which Embedded Signup flow the link should trigger.
 * - "coexistence": the number keeps working in the WhatsApp Business app.
 * - "api_only": the number (new or already in use) gets dedicated fully to
 *   the Cloud API; it stops working in any WhatsApp app once connected.
 */
export type OnboardMode = "coexistence" | "api_only";

export function isOnboardMode(value: unknown): value is OnboardMode {
  return value === "coexistence" || value === "api_only";
}

/**
 * Links never expired before this (an HMAC alone, with no persistence to
 * mark a link "used", stays valid forever — anyone who later obtains it,
 * e.g. forwarded by mistake, could still trigger a real Facebook OAuth grant
 * under the client's name). Capping the lifetime closes most of that window
 * without needing a database.
 */
const LINK_MAX_AGE_MS = 30 * 24 * 60 * 60 * 1000; // 30 days

function isFiniteTimestamp(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value);
}

/** Signed payload is `clientName|mode|ts`, so a link can't be replayed with a different mode, or past its generation time + max age, than what it was issued for. */
function signaturePayload(
  clientName: string,
  mode: OnboardMode,
  ts: number,
): string {
  return `${clientName.trim()}|${mode}|${ts}`;
}

/** Deterministic signature, truncated to 32 hex chars (128 bits), plenty for this and keeps the URL short. */
export function signClientName(
  clientName: string,
  mode: OnboardMode,
  ts: number,
  secret: string,
): string {
  return createHmac("sha256", secret)
    .update(signaturePayload(clientName, mode, ts))
    .digest("hex")
    .slice(0, 32);
}

/** Constant-time comparison so a failed attempt can't be used to brute-force the signature byte by byte via timing. */
export function verifyClientSignature(
  clientName: string,
  mode: unknown,
  ts: unknown,
  sig: string,
  secret: string,
): boolean {
  const tsNum = typeof ts === "string" ? Number(ts) : ts;
  if (
    !clientName.trim() ||
    !sig ||
    !isOnboardMode(mode) ||
    !isFiniteTimestamp(tsNum)
  ) {
    return false;
  }
  if (Date.now() - tsNum > LINK_MAX_AGE_MS || tsNum > Date.now()) return false;

  const expected = signClientName(clientName, mode, tsNum, secret);
  const expectedBuf = Buffer.from(expected, "utf8");
  const sigBuf = Buffer.from(sig, "utf8");

  if (expectedBuf.length !== sigBuf.length) return false;
  return timingSafeEqual(expectedBuf, sigBuf);
}

/** Builds the full onboarding URL (both locale variants) for a given client name + mode. */
export function buildOnboardingUrls(
  clientName: string,
  mode: OnboardMode,
  secret: string,
  siteUrl: string,
): { es: string; en: string } {
  // Normalize so a bare domain (easy to paste by mistake, e.g. when testing
  // through a tunnel) still produces a full, shareable https:// link —
  // sharing a protocol-less URL breaks link-preview metadata on WhatsApp/etc.
  let base = siteUrl.trim().replace(/\/$/, "");
  if (!/^https?:\/\//i.test(base)) base = `https://${base}`;

  const ts = Date.now();
  const sig = signClientName(clientName, mode, ts, secret);
  const query = `?cliente=${encodeURIComponent(clientName)}&modo=${mode}&ts=${ts}&sig=${sig}`;
  return {
    es: `${base}/es/conectar/${query}`,
    en: `${base}/en/connect/${query}`,
  };
}

/** Constant-time string comparison for secrets that aren't HMACs of our own data (e.g. an admin token typed back at us). */
export function timingSafeStringEqual(a: string, b: string): boolean {
  const aBuf = Buffer.from(a, "utf8");
  const bBuf = Buffer.from(b, "utf8");
  if (aBuf.length !== bBuf.length) return false;
  return timingSafeEqual(aBuf, bBuf);
}
